name: Trigger Vercel Redeploy

on:
    workflow_dispatch:

jobs:
    redeploy:
        runs-on: ubuntu-latest
        steps:
            - name: Call Vercel deploy hook
              run: curl -X POST ${{ secrets.VERCEL_RDP_HOOK }}
