name: Trigger Vercel Redeploy

on:
    workflow_dispatch:

jobs:
    redeploy:
        runs-on: ubuntu-latest
        steps:
            - name: Call Vercel deploy hook
              run: |
                  response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.VERCEL_RDP_HOOK }})
